[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["A J Blakie <ajblakie@tutanota.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
